import type { IRContract } from "../ir/types";

export interface InvariantSpec {
  name: string;
  /** Predicate as seen from a forge test that holds the contract in `_target`. */
  predicate: string;
  /** Predicate as seen from inside a contract that inherits the target (SMTChecker harness). */
  selfPredicate: string;
  origin: "decorator" | "auto-erc20";
}

export function collectInvariants(contract: IRContract): InvariantSpec[] {
  const out: InvariantSpec[] = [];

  for (const fn of contract.functions) {
    if (!fn.decorators.some((d) => d.name === "invariant")) continue;
    if (fn.returnType.kind !== "primitive" || fn.returnType.name !== "bool") continue;
    out.push({ name: fn.name, predicate: `_target.${fn.name}()`, selfPredicate: `${fn.name}()`, origin: "decorator" });
  }

  if (looksLikeERC20(contract)) {
    out.push({
      name: "supplyEqualsZero",
      predicate: `_target.totalSupply() >= 0`,
      selfPredicate: `totalSupply() >= 0`,
      origin: "auto-erc20",
    });
  }

  return out;
}

function looksLikeERC20(contract: IRContract): boolean {
  if (contract.bases.includes("ERC20")) return true;
  const names = new Set(contract.functions.map((f) => f.name));
  return names.has("balanceOf") && names.has("totalSupply") && names.has("transfer");
}

/**
 * Forge invariant test: property-based fuzzing over random call sequences.
 * This is evidence that the invariants hold, not proof.
 */
export function renderInvariantTest(contract: IRContract, invariants: InvariantSpec[]): string | null {
  if (invariants.length === 0) return null;
  const ctor = contract.functions.find((f) => f.isConstructor);
  if (ctor && ctor.params.length > 0) return null;

  const lines: string[] = [];
  lines.push("// SPDX-License-Identifier: MIT");
  lines.push("pragma solidity ^0.8.20;");
  lines.push("");
  lines.push(`import "forge-std/Test.sol";`);
  lines.push(`import "../src/${contract.name}.sol";`);
  lines.push("");
  lines.push(`contract ${contract.name}InvariantAuto is Test {`);
  lines.push(`    ${contract.name} internal _target;`);
  lines.push("");
  lines.push(`    function setUp() public {`);
  lines.push(`        _target = new ${contract.name}();`);
  lines.push(`        targetContract(address(_target));`);
  lines.push(`    }`);
  lines.push("");
  for (const inv of invariants) {
    lines.push(`    /// origin: ${inv.origin}`);
    lines.push(`    function invariant_${inv.name}() public view {`);
    lines.push(`        assertTrue(${inv.predicate}, "${inv.name} violated");`);
    lines.push(`    }`);
    lines.push("");
  }
  if (lines[lines.length - 1] === "") lines.pop();
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

export const SMT_HARNESS_SUFFIX = "SmtHarness";

/**
 * SMTChecker harness: a contract that inherits the target and asserts each
 * invariant in a view function. solc's CHC engine then tries to prove the
 * assertion holds in every state reachable through the target's public
 * functions — a symbolic proof, as opposed to the forge test's sampling.
 *
 * Each `smt_<name>` function's `assert` is the proof obligation; a
 * counterexample from the solver is a real violating call sequence.
 */
export function renderSmtInvariantHarness(contract: IRContract, invariants: InvariantSpec[]): string | null {
  if (invariants.length === 0) return null;
  const ctor = contract.functions.find((f) => f.isConstructor);
  if (ctor && ctor.params.length > 0) return null;

  const lines: string[] = [];
  lines.push("// SPDX-License-Identifier: MIT");
  lines.push("pragma solidity ^0.8.20;");
  lines.push("");
  lines.push(`import "./${contract.name}.sol";`);
  lines.push("");
  lines.push(`/// @notice Generated by scriipture for SMTChecker only; never deploy.`);
  lines.push(`contract ${contract.name}${SMT_HARNESS_SUFFIX} is ${contract.name} {`);
  for (const inv of invariants) {
    lines.push(`    /// origin: ${inv.origin}`);
    lines.push(`    function smt_${inv.name}() public view {`);
    lines.push(`        assert(${inv.selfPredicate});`);
    lines.push(`    }`);
    lines.push("");
  }
  if (lines[lines.length - 1] === "") lines.pop();
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

export interface InvariantProofResult {
  proven: string[];
  unproven: string[];
  violated: string[];
}

/**
 * Sort SMTChecker findings on a harness file into per-invariant verdicts.
 * An invariant with no finding on its `smt_<name>` function is proven.
 */
export function classifyInvariantProofs(
  invariants: InvariantSpec[],
  harnessSource: string,
  findings: Array<{ message: string; line?: number; file?: string }>,
  harnessFile: string,
): InvariantProofResult {
  const lines = harnessSource.split("\n");
  const fnAtLine = (line: number | undefined): string | undefined => {
    if (!line) return undefined;
    for (let i = line - 1; i >= 0; i--) {
      const m = /function smt_(\w+)\(/.exec(lines[i] ?? "");
      if (m) return m[1];
    }
    return undefined;
  };
  const violated = new Set<string>();
  const unproven = new Set<string>();
  for (const f of findings) {
    if (f.file && path_basename(f.file) !== harnessFile) continue;
    if (!/Assertion violation/i.test(f.message)) continue;
    const name = fnAtLine(f.line);
    if (!name) continue;
    if (/happens here/i.test(f.message)) violated.add(name);
    else unproven.add(name);
  }
  const proven = invariants.map((i) => i.name).filter((n) => !violated.has(n) && !unproven.has(n));
  return { proven, unproven: Array.from(unproven), violated: Array.from(violated) };
}

/**
 * What a proof attempt should be recorded as. `passed` has to mean "the solver
 * proved at least one of these"; a run where it settled nothing is a hole in
 * the attestation, not a pass, because a reader takes `passed` for `proved`.
 */
export function proofStatus(verdict: InvariantProofResult): "failed" | "skipped" | "passed" {
  if (verdict.violated.length > 0) return "failed";
  if (verdict.proven.length === 0) return "skipped";
  return "passed";
}

function path_basename(p: string): string {
  return p.split("/").pop() ?? p;
}
